# Generated by Django 4.0.6 on 2022-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
