# Generated by Django 4.0.6 on 2022-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_departments_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
